version: '3.7'
services:
   api:
      image: cristhiankr/pluss_api:v1
      # build: .
      container_name: api_pluss
      command: ["import time", "time.sleep(15) # Delay for 5 seconds"]
      # command: python manage.py migrate
      command: python manage.py runserver 0.0.0.0:8000
      environment: 
        HOST_DB: postgres
      links:
        - db:postgres
      # volumes:
      #   - .:/api
      ports:
        - "8000:8000" 
      depends_on:
        - db
   db:
      image: postgres:12.0-alpine
      container_name: db_pluss
      ports:
        - "5433:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_USER: pluss
        POSTGRES_DB: cotizaciones_pluss
        POSTGRES_PASSWORD: maestr8_kar1n
          
volumes: 
   postgres_data:
