version: '3'
services:
   api:
      # image: cristhiankr/pluss_api:v1
      image: pluss_api
      container_name: api_pluss
      command: python manage.py runserver 0.0.0.0:8933
      ports:
        - "8933:8933" 
      volumes:
        - .:/api
      environment:
        HOST_DB: postgres
      links:
        - db:postgres
      depends_on:
        - db
   db:
      image: postgres:12.0-alpine
      # container_name: db_pluss
      ports:
        - "5433:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_USER: pluss
        POSTGRES_DB: pluss_db
        POSTGRES_PASSWORD: maestr8_kar1n
          
volumes: 
   postgres_data:
