version: '3'
services:
   api:
      image: cristhiankr/pluss_api:prod
      container_name: api_pluss
      # command: ["import time", "time.sleep(15) # Delay for 5 seconds"]
      # command: apt-get install wkhtmltopdf
      # command: python manage.py migrate
      command: python manage.py runserver 0.0.0.0:8933
      ports:
        - "8933:8933"
   www: 
      image: nginx
      container_name: www
      restart: always
      depends_on: 
        - www 
      volumes: 
        - share-volumen-pluss-web:/usr/share/nginx/html:ro
      ports:
        - "80:80"
   pluss-web:
      image: cristhiankr/pluss_web:prod
      container_name: web
      volumes:      
        - share-volumen-pluss-web:/pluss_web/build

volumes: 
  share-volumen-pluss-web: