# Generated by Django 2.2.7 on 2019-11-21 04:17

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre cliente')),
                ('phone', models.CharField(max_length=30, verbose_name='Número telefónico')),
                ('agent', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Asesor de venta')),
                ('city', models.CharField(max_length=150, verbose_name='Ciudad')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Clientes',
                'db_table': 'cp_client',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illustration', models.CharField(max_length=500, verbose_name='Imagen')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('detail', models.CharField(max_length=500, verbose_name='Descripción del producto')),
                ('measurements', models.CharField(max_length=20, verbose_name='Medidas')),
                ('color', models.CharField(max_length=50, verbose_name='colores disponibles')),
                ('mark_type', models.CharField(max_length=50, verbose_name='Tipo de marcación')),
                ('material', models.CharField(max_length=50, verbose_name='Material del producto')),
            ],
            options={
                'verbose_name': 'Productos',
                'db_table': 'cp_product',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.CharField(max_length=5, verbose_name='Tiempo de entrega')),
                ('pay_format', models.CharField(max_length=10, verbose_name='Formato de pago')),
                ('units', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Unidades a evaluar')),
                ('cost', models.CharField(max_length=20, verbose_name='Costo')),
                ('discount_rate', models.CharField(max_length=5, verbose_name='Porcentaje de descuento')),
                ('mark', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Marcación')),
                ('profitability_rate', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Porcentaje de rentabilidad')),
                ('sale_value', models.CharField(max_length=50, verbose_name='Valor venta')),
                ('transport', models.CharField(max_length=20, verbose_name='Precio transporte')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client', verbose_name='cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo de ventas')),
            ],
            options={
                'verbose_name': 'Cotización',
                'db_table': 'cp_quotation',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Código usuario')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Número telefónico')),
                ('type_identification', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('P', 'Pasaporte')], max_length=50, verbose_name='Tipo de identificación')),
                ('identification_number', models.CharField(max_length=20, unique=True, verbose_name='Documento')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Tipo de usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'db_table': 'cp_profile',
            },
        ),
    ]
