# Generated by Django 2.2.7 on 2019-12-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=50, null=True, verbose_name='colores disponibles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='illustration',
            field=models.CharField(max_length=500, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mark_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Tipo de marcación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=50, null=True, verbose_name='Material del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurements',
            field=models.CharField(max_length=20, null=True, verbose_name='Medidas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='cost',
            field=models.CharField(max_length=20, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='delivery_time',
            field=models.CharField(max_length=5, null=True, verbose_name='Tiempo de entrega'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='discount_rate',
            field=models.CharField(max_length=5, null=True, verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pay_format',
            field=models.CharField(max_length=10, null=True, verbose_name='Formato de pago'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sale_value',
            field=models.CharField(max_length=50, null=True, verbose_name='Valor venta'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='transport',
            field=models.CharField(max_length=20, null=True, verbose_name='Precio transporte'),
        ),
    ]
