# Generated by Django 2.2.7 on 2020-01-15 17:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191201_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='profitability_rate',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='sale_value',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='transport',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Número telefónico'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=150, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_two',
            field=models.CharField(max_length=30, null=True, verbose_name='Número telefónico'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='products',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='2020-01-15', verbose_name='Productos'),
            preserve_default=False,
        ),
    ]
