# Generated by Django 2.2.7 on 2020-02-03 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200115_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dependece',
            field=models.CharField(default='progreso', max_length=100, verbose_name='Dependencia o área'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='nit',
            field=models.CharField(default=123456, max_length=25, verbose_name='Nit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='En progreso', max_length=20, verbose_name='Estado cotización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.CharField(max_length=150, verbose_name='Asesor de venta'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=150, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_two',
            field=models.CharField(max_length=30, null=True, verbose_name='Número telefónico alternativo'),
        ),
    ]
