# Generated by Django 2.2.7 on 2020-01-21 03:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200115_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Info temporal')),
            ],
            options={
                'verbose_name': 'Cotización temporal',
                'db_table': 'cp_quotationTemp',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Información adiccional'),
        ),
        migrations.AddField(
            model_name='product',
            name='provier_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Nombre del proveedor'),
        ),
        migrations.AddField(
            model_name='product',
            name='referency_id',
            field=models.CharField(max_length=64, null=True, verbose_name='Identificador producto'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=150, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_two',
            field=models.CharField(max_length=30, null=True, verbose_name='Número telefónico alyternativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=128, null=True, verbose_name='colores disponibles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='illustration',
            field=models.CharField(max_length=512, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mark_type',
            field=models.CharField(max_length=128, null=True, verbose_name='Tipo de marcación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=128, null=True, verbose_name='Material del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurements',
            field=models.CharField(max_length=128, null=True, verbose_name='Medidas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Nombre del producto'),
        ),
    ]
